-- =====================================================
-- OpenDesk Database Schema with Authentication
-- =====================================================

-- Create resources table
create table if not exists resources (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  category text not null,
  address text not null,
  pincode text,
  coordinates float[] not null, -- stored as array [lat, lng]
  hours text,
  facilities text[], -- stored as array of strings
  cost text check (cost in ('Free', 'Low-cost')),
  contact text,
  description text,
  status text default 'Pending' check (status in ('Pending', 'Approved', 'Rejected')),
  submitted_by text,
  user_id uuid references auth.users(id) -- Link to authenticated user
);

-- Create admin_users table to track admin privileges
create table if not exists admin_users (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  role text default 'admin' check (role in ('admin', 'super_admin')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table resources enable row level security;
alter table admin_users enable row level security;

-- =====================================================
-- RLS Policies for Resources
-- =====================================================

-- Drop existing policies if they exist
drop policy if exists "Allow public read access" on resources;
drop policy if exists "Allow public insert access" on resources;
drop policy if exists "Allow read all for demo" on resources;
drop policy if exists "Allow authenticated users to insert" on resources;
drop policy if exists "Allow admins to read all" on resources;
drop policy if exists "Allow admins to update" on resources;

-- Policy: Allow public read access to Approved resources
create policy "Allow public read access"
  on resources for select
  using (status = 'Approved');

-- Policy: Allow authenticated users to insert resources
create policy "Allow authenticated users to insert"
  on resources for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Policy: Allow admins to read all resources (including pending)
create policy "Allow admins to read all"
  on resources for select
  to authenticated
  using (
    exists (
      select 1 from admin_users
      where admin_users.id = auth.uid()
    )
  );

-- Policy: Allow admins to update resources (approve/reject)
create policy "Allow admins to update"
  on resources for update
  to authenticated
  using (
    exists (
      select 1 from admin_users
      where admin_users.id = auth.uid()
    )
  );

-- =====================================================
-- RLS Policies for Admin Users
-- =====================================================

-- Policy: Allow admins to read admin_users table
create policy "Allow admins to read admin_users"
  on admin_users for select
  to authenticated
  using (
    exists (
      select 1 from admin_users
      where admin_users.id = auth.uid()
    )
  );

-- =====================================================
-- Functions and Triggers
-- =====================================================

create or replace function set_resource_user_id()
returns trigger as $$
begin
  -- Only set user_id from auth.uid() if it's available (context is authenticated user)
  -- AND if user_id wasn't already passed explicitly
  if auth.uid() is not null and new.user_id is null then
    new.user_id = auth.uid();
  end if;
  
  -- Set submitted_by to user's email if not provided and auth.uid() is available
  if new.submitted_by is null and auth.uid() is not null then
    new.submitted_by = (select email from auth.users where id = auth.uid());
  end if;
  
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function before insert
drop trigger if exists set_resource_user_id_trigger on resources;
create trigger set_resource_user_id_trigger
  before insert on resources
  for each row
  execute function set_resource_user_id();

-- =====================================================
-- Insert Mock Data
-- =====================================================

-- Note: These inserts will work for public approved resources
-- For pending resources with user_id, you'll need to insert after creating users

insert into resources (name, category, address, pincode, coordinates, hours, facilities, cost, contact, description, status, submitted_by)
values
  ('Central Public Library', 'Libraries', '12 Main St, District A', '110001', '{28.6139, 77.2090}', '9:00 AM - 5:00 PM', '{"Wi-Fi", "Seating", "Books", "Electricity"}', 'Free', '011-23456789', 'A large public library with a vast collection of books and quiet study areas.', 'Approved', 'System'),
  ('Sunrise Community Center', 'Community Classrooms', '45 Village Rd, District B', '201301', '{28.5355, 77.3910}', '10:00 AM - 6:00 PM', '{"Seating", "Electricity", "Mentors"}', 'Free', '9876543210', 'Community-run center providing free tuition and study space for local students.', 'Approved', 'System'),
  ('TechHub NGO', 'Public Wi-Fi', '88 Tech Park, District C', '122001', '{28.4595, 77.0266}', '24/7', '{"Wi-Fi", "Charging Ports"}', 'Free', 'hello@techhub.org', 'Free high-speed Wi-Fi zone for students and job seekers.', 'Approved', 'System'),
  ('Knowledge Book Bank', 'Book Banks', 'Sector 14, District A', '110085', '{28.7041, 77.1025}', '11:00 AM - 4:00 PM (Sat-Sun)', '{"Books", "Donations"}', 'Low-cost', 'books@knowledge.org', 'Borrow textbooks and reference materials for a nominal fee.', 'Approved', 'System'),
  ('Late Night Study Hall', 'Study Centers', 'University Road, District A', '110007', '{28.6921, 77.2120}', '6:00 PM - 2:00 AM', '{"Seating", "Electricity", "Water", "Security"}', 'Low-cost', '011-98765432', 'Safe and quiet study space available for late-night preparation.', 'Approved', 'System'),
  ('Greenfield Park Zone', 'Public Wi-Fi', 'Greenfield Park, District B', '201301', '{28.5700, 77.3200}', '6:00 AM - 10:00 PM', '{"Wi-Fi", "Open Air Seating"}', 'Free', 'N/A', 'Public park with free municipal Wi-Fi access.', 'Approved', 'System'),
  ('Hope Foundation Tutor Center', 'Free Tuition NGOs', 'Slum Colony A, District C', '122001', '{28.4800, 77.0800}', '4:00 PM - 7:00 PM', '{"Tuition", "Books"}', 'Free', 'hope@foundation.org', 'Free after-school tuition for classes 1-10.', 'Approved', 'System')
on conflict do nothing;

-- =====================================================
-- Instructions for Admin Setup
-- =====================================================

-- After creating your first admin user via Supabase Auth signup, run:
-- insert into admin_users (id, email, role)
-- values ('USER_UUID_HERE', 'admin@example.com', 'admin');

-- Or use this query to make an existing user an admin:
-- insert into admin_users (id, email, role)
-- select id, email, 'admin'
-- from auth.users
-- where email = 'your-email@example.com';
